# Generated by Django 5.0.6 on 2026-06-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
