# Generated by Django 5.0.6 on 2026-06-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrollment_no',
            field=models.CharField(blank=True, default='', max_length=8, unique=True),
        ),
    ]
