# Generated by Django 5.0.6 on 2026-06-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_populate_enrollment_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enrollment_no',
            field=models.CharField(blank=True, default='', max_length=8, unique=True),
        ),
    ]
